CREATE TABLE directories (
  id SERIAL PRIMARY KEY,
  owner SERIAL NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  parent INTEGER REFERENCES directories(id) DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  public BOOLEAN NOT NULL DEFAULT FALSE
);